// Generated by scripts/build-story-data.mjs from reviewed story packets and explicit runtime policy.
import type { AdventureDefinition } from './registry';
export const NEW_ADVENTURES: AdventureDefinition[] = [
  {
    "id": "last-flight-teacup",
    "version": 1,
    "title": "The Last Flight of the Teacup",
    "pitch": "Rescue a runaway postal airship. Choose what to bring home.",
    "chapters": [
      {
        "id": "teacup-dock",
        "title": "Catch the Teacup",
        "location": "Catch the Teacup",
        "intro": "Rescue a runaway postal airship. Choose what to bring home. Pella's ship is drifting with guests aboard. Secure a way onto the deck.",
        "catchUp": "Pella's ship is drifting with guests aboard. Secure a way onto the deck.",
        "objective": "Catch the airship before the last rope snaps.",
        "art": "teacup",
        "firstTarget": "teacup-mooring",
        "targets": [
          {
            "id": "teacup-mooring",
            "name": "Last rope",
            "artKey": "story-rope",
            "description": "Fight: haul; Investigate: locate sound anchor; Help: brace",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Last rope",
              "artKey": "story-rope",
              "description": "Secured boarding line → guide passengers across",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "teacup-pella",
            "name": "Captain Pella",
            "artKey": "story-pella",
            "description": "Influence: focus her orders; Investigate: ask about controls; Help: untangle coat",
            "tokens": [
              "influence",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Captain Pella",
              "artKey": "story-pella",
              "description": "Pella standing at rail → coordinate boarding",
              "tokens": [
                "influence",
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "teacup-parcels",
            "name": "Sliding parcels",
            "artKey": "story-parcels",
            "description": "Fight: wedge crates; Investigate: read emergency markings; Help: secure cargo",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Sliding parcels",
              "artKey": "story-parcels",
              "description": "Tied stack exposes lifeboat diagram → study escape route",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "teacup-guests",
            "name": "Festival guests",
            "artKey": "herd-gathered",
            "description": "Influence: calm; Help: catch a slipping guest",
            "tokens": [
              "influence",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Festival guests",
              "artKey": "herd-gathered",
              "description": "Guests holding safety line → organize evacuation",
              "tokens": [
                "influence",
                "assist"
              ]
            }
          }
        ],
        "progressGoal": 24,
        "combat": false,
        "threat": "The way forward is slipping out of reach.",
        "keepsake": "A knotted boarding cord",
        "endings": {
          "success": "The boarding line holds and everyone reaches the deck with the parcels intact. The lifeboat diagram shows a detachable sail canopy; a marked seam is the emergency vent.",
          "mixed": "Everyone reaches the deck, but loose parcels tumble into the clouds. The lifeboat diagram shows a detachable sail canopy; a marked seam is the emergency vent.",
          "setback": "The dock net catches the rescuers and is hauled aboard; the last mooring is lost. The lifeboat diagram shows a detachable sail canopy; a marked seam is the emergency vent."
        }
      },
      {
        "id": "teacup-cloudline",
        "title": "Above the Cloudline",
        "location": "Above the Cloudline",
        "intro": "The guests are aboard, but the ship cannot descend. Its safety gull mistakes the rescue for damage.",
        "catchUp": "The guests are aboard, but the ship cannot descend. Its safety gull mistakes the rescue for damage.",
        "objective": "Steady the deck and restart the kettle engine.",
        "art": "teacup",
        "firstTarget": "teacup-engine",
        "targets": [
          {
            "id": "teacup-engine",
            "name": "Kettle engine",
            "artKey": "story-kettle",
            "description": "Fight: loosen valve; Investigate: trace steam; Help: repair",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Kettle engine",
              "artKey": "story-kettle",
              "description": "Glowing kettle → regulate descent",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "teacup-sail",
            "name": "Festival sail",
            "artKey": "story-sail",
            "description": "Investigate: find vent seam; Influence: coordinate handlers; Help: tension ropes",
            "tokens": [
              "investigate",
              "influence",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Festival sail",
              "artKey": "story-sail",
              "description": "Marked vent seam → prepare the descent option",
              "tokens": [
                "investigate",
                "influence",
                "assist"
              ]
            }
          },
          {
            "id": "teacup-gull",
            "name": "Brass gull",
            "artKey": "story-gull",
            "description": "Fight: interrupt; Influence: mimic maintenance call; Investigate: identify command; Help: distract",
            "tokens": [
              "fight",
              "influence",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Brass gull",
              "artKey": "story-gull",
              "description": "Lowered beak and lit service symbol → keep it occupied",
              "tokens": [
                "influence",
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "teacup-lifeboat",
            "name": "Hanging lifeboat",
            "artKey": "boat-afloat",
            "description": "Fight: release winch; Investigate: inspect harnesses; Help: secure guests",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Hanging lifeboat",
              "artKey": "boat-afloat",
              "description": "Lifeboat level with deck → prepare evacuation",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          }
        ],
        "progressGoal": 26,
        "combat": true,
        "enemySource": "teacup-gull",
        "threat": "The brass gull dives at the exposed crew. Protect or interrupt the announced strike.",
        "keepsake": "A little brass feather",
        "endings": {
          "success": "The kettle glows and the ship steadies. Pella opens both escape routes. The vent tears the festival sail to save the ship. The lifeboat salvages the sail but leaves the ship behind.",
          "mixed": "The engine coughs, but the crew prepares both routes. The vent tears the festival sail to save the ship. The lifeboat salvages the sail but leaves the ship behind.",
          "setback": "The engine gives one last burst. Pella points to the vent and the lifeboat: both can save everyone. The vent tears the festival sail to save the ship. The lifeboat salvages the sail but leaves the ship behind."
        }
      },
      {
        "id": "teacup-homecoming",
        "title": "Something Worth Bringing Home",
        "location": "Something Worth Bringing Home",
        "intro": "The ship and its treasured sail cannot both survive intact. The prepared route shows how everyone can reach the dock.",
        "catchUp": "The ship and its treasured sail cannot both survive intact. The prepared route shows how everyone can reach the dock.",
        "objective": "Bring everyone home using the route you chose.",
        "art": "teacup",
        "firstTarget": "teacup-return-valve",
        "targets": [
          {
            "id": "teacup-return-valve",
            "name": "Vent handle",
            "artKey": "story-kettle",
            "description": "Fight: turn; Investigate: match pressure; Help: brace",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Vent handle",
              "artKey": "story-kettle",
              "description": "Released vent and torn sail on ship route → stabilize landing; on evacuation route, idle vent → steady abandoned ship while boarding",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "teacup-return-boat",
            "name": "Lifeboat cradle",
            "artKey": "boat-afloat",
            "description": "Fight: winch; Investigate: balance load; Help: transfer guests",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Lifeboat cradle",
              "artKey": "boat-afloat",
              "description": "Lifeboat occupied on evacuation route, safety platform on ship route → guide final passengers",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "teacup-return-guests",
            "name": "Passenger line",
            "artKey": "herd-gathered",
            "description": "Influence: coordinate; Help: support",
            "tokens": [
              "influence",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Passenger line",
              "artKey": "herd-gathered",
              "description": "Guests arriving on dock → clear landing area",
              "tokens": [
                "influence",
                "assist"
              ]
            }
          },
          {
            "id": "teacup-return-beacon",
            "name": "Home beacon",
            "artKey": "story-lantern",
            "description": "Investigate: find alignment; Influence: signal dock crew; Help: hold light",
            "tokens": [
              "investigate",
              "influence",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Home beacon",
              "artKey": "story-lantern",
              "description": "Bright approach path → guide final descent",
              "tokens": [
                "investigate",
                "influence",
                "assist"
              ]
            }
          }
        ],
        "progressGoal": 30,
        "combat": false,
        "threat": "The final opportunity is closing.",
        "keepsake": "Pella’s dented brass badge",
        "endings": {
          "success": "Everyone reaches the dock safely. Pella opens a shared rescue service. Pella hangs a new sign: People first. Parcels when possible.",
          "mixed": "Everyone reaches the dock; neighbors gather the scattered parcels. Pella hangs a new sign: People first. Parcels when possible.",
          "setback": "The guests land in the emergency nets. Neighbors build a temporary shelter. Pella hangs a new sign: People first. Parcels when possible."
        },
        "branch": {
          "prompt": "What will you bring home?",
          "fallback": "lifeboat",
          "fallbackText": "Tie or no choice: take the lifeboat. Everyone and the sail return; the ship is lost.",
          "options": [
            {
              "id": "vent",
              "targetId": "teacup-return-valve",
              "label": "Save the ship",
              "consequence": "Tear the festival sail to descend. Everyone returns; the sail is lost."
            },
            {
              "id": "lifeboat",
              "targetId": "teacup-return-boat",
              "label": "Save the sail",
              "consequence": "Salvage it as the lifeboat canopy. Everyone returns; the ship is lost."
            }
          ]
        }
      }
    ],
    "branchEndings": {
      "vent": "The torn sail hangs from the battered airship; its cloth cannot be restored. The crew shares what remains.",
      "lifeboat": "The airship is gone. Its salvaged sail roofs a new ferry shelter at the dock."
    },
    "closing": {
      "vent": {
        "artKey": "story-sail-torn",
        "caption": "A torn sail. A rescued crew. A new purpose."
      },
      "lifeboat": {
        "artKey": "story-sail",
        "caption": "The ship is gone. Its sail shelters the next rescue."
      }
    }
  },
  {
    "id": "inn-misplaced-tomorrow",
    "version": 1,
    "title": "The Inn That Misplaced Tomorrow",
    "pitch": "Find the missing dawn inside an inn stuck at breakfast.",
    "chapters": [
      {
        "id": "tomorrow-breakfast",
        "title": "The Coldest Breakfast",
        "location": "The Coldest Breakfast",
        "intro": "Find the missing dawn inside an inn stuck at breakfast. Morning is stuck on one repeated moment. Something behind the clock is collecting the sounds.",
        "catchUp": "Morning is stuck on one repeated moment. Something behind the clock is collecting the sounds.",
        "objective": "Find why breakfast keeps starting over.",
        "art": "tomorrow",
        "firstTarget": "tomorrow-spoon",
        "targets": [
          {
            "id": "tomorrow-spoon",
            "name": "Falling spoon",
            "artKey": "story-spoon",
            "description": "Investigate: follow its repeat; Help: catch and mark",
            "tokens": [
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Falling spoon",
              "artKey": "story-spoon",
              "description": "Marked spoon stops repeating locally → compare nearby loops",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "tomorrow-brindle",
            "name": "Brindle",
            "artKey": "story-brindle",
            "description": "Influence: ask for help; Investigate: question his instruction; Help: calm him",
            "tokens": [
              "influence",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Brindle",
              "artKey": "story-brindle",
              "description": "Apron loosened, note in hand → reveal the exact command",
              "tokens": [
                "influence",
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "tomorrow-clock",
            "name": "Breakfast clock",
            "artKey": "story-clock",
            "description": "Fight: free jammed casing; Investigate: follow ticking; Help: steady gears",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Breakfast clock",
              "artKey": "story-clock-open",
              "description": "Open clock doorway → guide party inside",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "tomorrow-toast",
            "name": "Stubborn toast",
            "artKey": "story-toast",
            "description": "Fight: lift jammed rack; Investigate: trace the heat; Help: shield hands",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Stubborn toast",
              "artKey": "story-toast",
              "description": "Warm crumbs point toward clock → mark workshop route",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          }
        ],
        "progressGoal": 24,
        "combat": false,
        "threat": "The way forward is slipping out of reach.",
        "keepsake": "A marked toast crumb",
        "endings": {
          "success": "The clock opens. Brindle admits asking his helper to make the perfect morning last. The note reads: make this morning last. The helper has followed it literally.",
          "mixed": "Burnt toast reveals the workshop door behind the clock. The note reads: make this morning last. The helper has followed it literally.",
          "setback": "The clock coughs its door open and ejects Brindle’s note. The note reads: make this morning last. The helper has followed it literally."
        }
      },
      {
        "id": "tomorrow-workshop",
        "title": "The Collector of Mornings",
        "location": "The Collector of Mornings",
        "intro": "Brindle asked for a perfect morning to last. His helper stored the dawn so morning could never end.",
        "catchUp": "Brindle asked for a perfect morning to last. His helper stored the dawn so morning could never end.",
        "objective": "Recover the dawn chime from the clockwork helper.",
        "art": "tomorrow",
        "firstTarget": "tomorrow-jars",
        "targets": [
          {
            "id": "tomorrow-jars",
            "name": "Sound jars",
            "artKey": "story-jar",
            "description": "Investigate: inspect symbols; Influence: hum to matching jars; Help: steady shelf",
            "tokens": [
              "investigate",
              "influence",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Sound jars",
              "artKey": "story-jar",
              "description": "Dawn jar glows beside rooster symbol → isolate the right note",
              "tokens": [
                "investigate",
                "influence",
                "assist"
              ]
            }
          },
          {
            "id": "tomorrow-helper",
            "name": "Tock",
            "artKey": "story-tock",
            "description": "Influence: acknowledge its work; Investigate: ask about command; Help: repair grip",
            "tokens": [
              "influence",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Tock",
              "artKey": "story-tock",
              "description": "Tock offers the dawn jar → cooperate on release",
              "tokens": [
                "influence",
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "tomorrow-recipe",
            "name": "Recipe cylinder",
            "artKey": "story-cylinder",
            "description": "Fight: loosen spindle; Investigate: read routine; Help: uncouple gear",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Recipe cylinder",
              "artKey": "story-cylinder",
              "description": "Cylinder exposed → prepare routine-unwinding route",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "tomorrow-memory",
            "name": "Memory spool",
            "artKey": "story-spool",
            "description": "Investigate: inspect stored breakfast pattern; Influence: explain alternative to Tock; Help: connect safe lead",
            "tokens": [
              "investigate",
              "influence",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Memory spool",
              "artKey": "story-spool",
              "description": "Spool in a protective cradle → prepare memory-spending route",
              "tokens": [
                "investigate",
                "influence",
                "assist"
              ]
            }
          }
        ],
        "progressGoal": 26,
        "combat": false,
        "threat": "The situation tightens while the party works.",
        "keepsake": "A tiny dawn jar",
        "endings": {
          "success": "Tock gladly offers the dawn chime. Both sustaining patterns are exposed. Two cables bind the chime: the perfect recipe or Tock’s breakfast memory must be spent to free it.",
          "mixed": "The party catches the glowing jar as its shelf collapses. Two cables bind the chime: the perfect recipe or Tock’s breakfast memory must be spent to free it.",
          "setback": "Tock delivers the jar before the collection can shatter. Two cables bind the chime: the perfect recipe or Tock’s breakfast memory must be spent to free it."
        }
      },
      {
        "id": "tomorrow-new-morning",
        "title": "A Morning Allowed to Happen",
        "location": "A Morning Allowed to Happen",
        "intro": "The dawn is safe in its jar. Releasing it will cost the perfect routine or Tock's memory of making it.",
        "catchUp": "The dawn is safe in its jar. Releasing it will cost the perfect routine or Tock's memory of making it.",
        "objective": "Release the chime and let the day begin.",
        "art": "tomorrow",
        "firstTarget": "tomorrow-return-recipe",
        "targets": [
          {
            "id": "tomorrow-return-recipe",
            "name": "Perfect recipe",
            "artKey": "story-cylinder",
            "description": "Fight: turn release crank; Investigate: unwind safely; Help: support cylinder",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Perfect recipe",
              "artKey": "story-cylinder",
              "description": "Blank cylinder if spent, preserved recipe otherwise → support the selected release circuit",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "tomorrow-return-memory",
            "name": "Breakfast memory",
            "artKey": "story-spool",
            "description": "Investigate: guide transfer; Influence: reassure Tock; Help: support cradle",
            "tokens": [
              "investigate",
              "influence",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Breakfast memory",
              "artKey": "story-spool",
              "description": "Empty breakfast spool if spent, intact spool otherwise → help Tock steady the chime",
              "tokens": [
                "investigate",
                "influence",
                "assist"
              ]
            }
          },
          {
            "id": "tomorrow-return-clock",
            "name": "Window clock",
            "artKey": "story-clock",
            "description": "Fight: free bell arm; Investigate: align symbols; Help: seat jar",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Window clock",
              "artKey": "story-clock-open",
              "description": "Clock sounding in sunlight → stabilize ordinary time",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "tomorrow-return-table",
            "name": "Waiting table",
            "artKey": "story-breakfast",
            "description": "Influence: organize guests; Help: share breakfast",
            "tokens": [
              "influence",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Waiting table",
              "artKey": "story-breakfast",
              "description": "Imperfect shared meal and extra chair → welcome Tock",
              "tokens": [
                "influence",
                "assist"
              ]
            }
          }
        ],
        "progressGoal": 30,
        "combat": false,
        "threat": "The final opportunity is closing.",
        "keepsake": "A mismatched breakfast spoon",
        "endings": {
          "success": "Sunlight moves over a warm, uneven breakfast. Brindle pulls up a chair for Tock. The spoon falls. This time, someone picks it up.",
          "mixed": "Morning returns amid burnt toast. Neighbors bring food to share. The spoon falls. This time, someone picks it up.",
          "setback": "The clock stops working, but ordinary sunrise returns. Brindle fetches a hand bell. The spoon falls. This time, someone picks it up."
        },
        "branch": {
          "prompt": "What will you let go?",
          "fallback": "recipe",
          "fallbackText": "Tie or no choice: unwind the recipe and preserve Tock’s memories.",
          "options": [
            {
              "id": "recipe",
              "targetId": "tomorrow-return-recipe",
              "label": "Keep the memories",
              "consequence": "Unwind the perfect recipe. Tock remembers; breakfast becomes an experiment."
            },
            {
              "id": "memory",
              "targetId": "tomorrow-return-memory",
              "label": "Keep the recipe",
              "consequence": "Spend only Tock’s learned breakfast routine. Help it relearn; its identity and friendships remain."
            }
          ]
        }
      }
    ],
    "branchEndings": {
      "recipe": "The recipe cylinder is blank. Tock remembers each shared morning, and everyone helps invent the next.",
      "memory": "The recipe survives. Tock’s breakfast spool is empty; Brindle sits beside it to teach the routine again."
    },
    "closing": {
      "recipe": {
        "artKey": "story-cylinder-blank",
        "caption": "The recipe is gone. Tomorrow is yours to invent."
      },
      "memory": {
        "artKey": "story-spool-empty",
        "caption": "An empty breakfast spool. A friend ready to teach."
      }
    }
  },
  {
    "id": "orchard-walked-away",
    "version": 1,
    "title": "The Orchard That Walked Away",
    "pitch": "Follow a wandering orchard and share the water it needs.",
    "chapters": [
      {
        "id": "orchard-departure",
        "title": "Empty Planting Circles",
        "location": "Empty Planting Circles",
        "intro": "Follow a wandering orchard and share the water it needs. The orchard has left its wall behind. A child is safely in its moving treehouse but needs help down.",
        "catchUp": "The orchard has left its wall behind. A child is safely in its moving treehouse but needs help down.",
        "objective": "Follow the trees and reach the stranded treehouse.",
        "art": "orchard",
        "firstTarget": "orchard-root-trail",
        "targets": [
          {
            "id": "orchard-root-trail",
            "name": "Root trail",
            "artKey": "story-roots",
            "description": "Investigate: follow moisture marks; Help: clear path",
            "tokens": [
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Root trail",
              "artKey": "story-roots",
              "description": "Marked dry footprints → guide villagers",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "orchard-nella",
            "name": "Gardener Nella",
            "artKey": "story-nella",
            "description": "Influence: organize search; Investigate: ask about watering; Help: carry basket",
            "tokens": [
              "influence",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Gardener Nella",
              "artKey": "story-nella",
              "description": "Nella holding old water map → compare changed stream",
              "tokens": [
                "influence",
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "orchard-gate",
            "name": "Orchard gate",
            "artKey": "gate",
            "description": "Fight: open jammed gate; Investigate: find root gap; Help: brace",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Orchard gate",
              "artKey": "gate-sheltered",
              "description": "Wide passage → move rescue equipment",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "orchard-ladder",
            "name": "Harvest ladder",
            "artKey": "story-ladder",
            "description": "Fight: free it from shed; Investigate: check joints; Help: lash rungs",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Harvest ladder",
              "artKey": "story-ladder",
              "description": "Braced ladder on wheels → follow treehouse",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          }
        ],
        "progressGoal": 24,
        "combat": false,
        "threat": "The way forward is slipping out of reach.",
        "keepsake": "A painted root marker",
        "endings": {
          "success": "The party reaches the trees with a steady harvest ladder. Dust coats the roots. Nella’s old map shows a stream where the soil is now dry.",
          "mixed": "The trees are found beyond a trail of spilled fruit. Dust coats the roots. Nella’s old map shows a stream where the soil is now dry.",
          "setback": "The trees pause at a low bank, creating a safe climb without the ladder. Dust coats the roots. Nella’s old map shows a stream where the soil is now dry."
        }
      },
      {
        "id": "orchard-dry-stream",
        "title": "Where the Water Went",
        "location": "Where the Water Went",
        "intro": "The trees stopped beside a dry stream. Water still runs through the ornamental mill uphill.",
        "catchUp": "The trees stopped beside a dry stream. Water still runs through the ornamental mill uphill.",
        "objective": "Reach the treehouse and restore a path for water.",
        "art": "orchard",
        "firstTarget": "orchard-treehouse",
        "targets": [
          {
            "id": "orchard-treehouse",
            "name": "Moving treehouse",
            "artKey": "story-treehouse",
            "description": "Influence: guide the child; Help: steady descent",
            "tokens": [
              "influence",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Moving treehouse",
              "artKey": "story-treehouse",
              "description": "Child on the bank, empty treehouse → use platform to signal trees",
              "tokens": [
                "influence",
                "assist"
              ]
            }
          },
          {
            "id": "orchard-elder",
            "name": "Elder Apple",
            "artKey": "story-appletree",
            "description": "Influence: listen; Investigate: inspect thirsty roots; Help: wet root cloth",
            "tokens": [
              "influence",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Elder Apple",
              "artKey": "story-appletree",
              "description": "Relaxed branches showing water marks → guide the migration",
              "tokens": [
                "influence",
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "orchard-sluice",
            "name": "Diverted sluice",
            "artKey": "story-sluice",
            "description": "Fight: move debris; Investigate: trace channels; Help: test gate",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Diverted sluice",
              "artKey": "story-sluice",
              "description": "Both water routes outlined → compare their costs",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "orchard-bramble",
            "name": "Bramble guardian",
            "artKey": "story-bramble",
            "description": "Fight: interrupt; Influence: soothe; Investigate: find seed signals; Help: shield others",
            "tokens": [
              "fight",
              "influence",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Bramble guardian",
              "artKey": "story-bramble",
              "description": "Thorns lowered around a damp patch → maintain safe passage",
              "tokens": [
                "influence",
                "investigate",
                "assist"
              ]
            }
          }
        ],
        "progressGoal": 26,
        "combat": true,
        "enemySource": "orchard-bramble",
        "threat": "The bramble guardian lashes toward an exposed hero. Protect or interrupt the announced strike.",
        "keepsake": "A woven root bracelet",
        "endings": {
          "success": "The child is safe, the guardian calms and both water routes are clear. The child is safe. The ornamental mill diverts the stream: open the orchard wall or retire the decorative wheel.",
          "mixed": "Everyone reaches the bank, though the bramble guardian remains wary. The child is safe. The ornamental mill diverts the stream: open the orchard wall or retire the decorative wheel.",
          "setback": "Elder Apple kneels to release the child. A burst sluice exposes both channels. The child is safe. The ornamental mill diverts the stream: open the orchard wall or retire the decorative wheel."
        }
      },
      {
        "id": "orchard-shared-harvest",
        "title": "A Place to Put Down Roots",
        "location": "A Place to Put Down Roots",
        "intro": "Everyone is safe, but the roots still need water. Choose what the village will change to welcome them.",
        "catchUp": "Everyone is safe, but the roots still need water. Choose what the village will change to welcome them.",
        "objective": "Open the water route and guide the harvest home.",
        "art": "orchard",
        "firstTarget": "orchard-return-wall",
        "targets": [
          {
            "id": "orchard-return-wall",
            "name": "Orchard wall",
            "artKey": "story-wall",
            "description": "Fight: lift stones; Investigate: mark spillway; Help: brace path",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Orchard wall",
              "artKey": "story-wall",
              "description": "Open water corridor if chosen, intact wall otherwise → stabilize chosen route without reversing cost",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "orchard-return-wheel",
            "name": "Mill wheel",
            "artKey": "story-mill",
            "description": "Fight: release brake; Investigate: redirect channel; Help: support mechanism",
            "tokens": [
              "fight",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Mill wheel",
              "artKey": "story-mill",
              "description": "Retired decorative wheel if chosen, turning wheel otherwise → regulate water safely",
              "tokens": [
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "orchard-return-roots",
            "name": "Waiting roots",
            "artKey": "story-appletree",
            "description": "Influence: call trees onward; Investigate: mark wet ground; Help: guide seedlings",
            "tokens": [
              "influence",
              "investigate",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Waiting roots",
              "artKey": "story-appletree",
              "description": "Trees settled beside water → tend new grove",
              "tokens": [
                "influence",
                "investigate",
                "assist"
              ]
            }
          },
          {
            "id": "orchard-return-baskets",
            "name": "Harvest baskets",
            "artKey": "story-baskets",
            "description": "Influence: organize sharing; Help: carry fruit",
            "tokens": [
              "influence",
              "assist"
            ],
            "effects": [
              "cover",
              "distract",
              "reveal",
              "rescue"
            ],
            "development": {
              "name": "Harvest baskets",
              "artKey": "story-baskets",
              "description": "Baskets distributed among neighbors → finish welcoming feast",
              "tokens": [
                "influence",
                "assist"
              ]
            }
          }
        ],
        "progressGoal": 30,
        "combat": false,
        "threat": "The final opportunity is closing.",
        "keepsake": "A carved apple seed",
        "endings": {
          "success": "The trees settle beside flowing water and the shared harvest begins. The baskets return. This year, everyone knows who watered the trees.",
          "mixed": "The nearer trees settle. Villagers arrange watering for those further away. The baskets return. This year, everyone knows who watered the trees.",
          "setback": "The trees settle at the public riverside; villagers carry baskets along a new path. The baskets return. This year, everyone knows who watered the trees."
        },
        "branch": {
          "prompt": "Make room for the water",
          "fallback": "spillway",
          "fallbackText": "Tie or no choice: open a small, reversible spillway through the wall.",
          "options": [
            {
              "id": "wall",
              "targetId": "orchard-return-wall",
              "label": "Share the grove",
              "consequence": "Open the orchard wall into a public water corridor. The mill keeps turning."
            },
            {
              "id": "wheel",
              "targetId": "orchard-return-wheel",
              "label": "Retire the mill",
              "consequence": "Stop the ornamental wheel and restore its channel. The sheltered orchard remains."
            }
          ]
        }
      }
    ],
    "branchEndings": {
      "wall": "The orchard wall is open to a shared water corridor. The ornamental mill still turns.",
      "wheel": "The decorative wheel stands still beside a new gathering space. Water reaches the sheltered orchard.",
      "spillway": "A small spillway waters the roots. Most of the wall remains, ready for a later community decision."
    },
    "closing": {
      "wall": {
        "artKey": "story-wall-open",
        "caption": "An open grove. Water and harvest shared."
      },
      "wheel": {
        "artKey": "story-mill",
        "caption": "The wheel rests. The orchard drinks again."
      },
      "spillway": {
        "artKey": "story-sluice",
        "caption": "A little spillway. A community deciding what comes next."
      }
    }
  }
];
